import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './catalog.css';
import {initialState, validExamples} from './preview-data.mjs';
const previewURL=(c,state)=>'/preview.html?'+new URLSearchParams({id:c.id,project:c.projectId,state:JSON.stringify(state)});
const initial=initialState;
function App(){
 const [manifest,setManifest]=useState(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[group,setGroup]=useState('All components'),[selected,setSelected]=useState(null),[state,setState]=useState(null),[variant,setVariant]=useState('Default'),[saved,setSaved]=useState({}),[events,setEvents]=useState([]),[renderErrors,setRenderErrors]=useState({}),[notice,setNotice]=useState(''),[exampleName,setExampleName]=useState('');
 const preview=useRef(null);
 const [page,setPage]=useState(0),[ready,setReady]=useState({}),[retry,setRetry]=useState(0);
 useEffect(()=>{setPage(0)},[search,group]);
 useEffect(()=>{fetch('/catalog.json').then(r=>{if(!r.ok)throw Error('Catalogue unavailable');return r.json()}).then(m=>{m.examples=validExamples(m.examples);setManifest(m);window.webkit?.messageHandlers?.componentCatalog?.postMessage({action:'catalogLoaded',projectId:m.projectId,ids:m.components.map(c=>c.id)});try{setSaved(JSON.parse(localStorage.getItem('wf:'+m.projectId)||'{}'));}catch{}}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{
  function receive(e){if(e.origin!==location.origin||!e.data?.webframes)return;
   const frame=[...document.querySelectorAll('iframe')].find(f=>f.contentWindow===e.source);if(!frame)return;
   const {kind,id,detail}=e.data;
   if(kind==='loading')setReady(v=>({...v,[id]:false}));
   if(kind==='error'){setRenderErrors(v=>({...v,[id]:detail}));setReady(v=>({...v,[id]:false}));}
   if(kind==='rendered'){setReady(v=>({...v,[id]:true}));setRenderErrors(v=>{const copy={...v};delete copy[id];return copy;});}
   if(kind==='event')setEvents(v=>[{...detail,time:new Date().toLocaleTimeString()},...v].slice(0,20));
  }addEventListener('message',receive);return()=>removeEventListener('message',receive);
 },[]);
 if(error)return <main><h1>Catalogue unavailable</h1><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></main>;
 if(!manifest)return <main><p>Discovering components…</p></main>;
 const groups=['All components',...new Set(manifest.components.map(c=>c.group))];
 const visible=manifest.components.filter(c=>(group==='All components'||c.group===group)&&`${c.name} ${c.source}`.toLowerCase().includes(search.toLowerCase()));
 function open(c){setSelected(c);setState(initial(c,manifest,saved));setVariant(manifest.examples[c.name]?.[0]?.name||'Default');setEvents([]);setNotice('');}
 function change(p,value){setState(s=>({...s,args:{...s.args,[p]:value}}));}
 function save(){const name=exampleName;if(!name.trim()){setNotice('Enter a name for this example.');return;}const next={...saved,[selected.id]:{...saved[selected.id],[name.trim()]:state}};try{localStorage.setItem('wf:'+manifest.projectId,JSON.stringify(next));setSaved(next);setVariant(name.trim());setNotice('Example saved on this Mac.');}catch{setNotice('Could not save this example. Local storage is full.');}}
 function add(){if(!ready[selected.id]||renderErrors[selected.id]){setNotice('Load a working preview before adding it to the canvas.');return;}const url=new URL(previewURL(selected,state),location.origin).href;
  if(window.webkit?.messageHandlers?.componentCatalog){window.webkit.messageHandlers.componentCatalog.postMessage({action:'addComponent',url,name:selected.name+' · '+variant,width:state.width,projectId:manifest.projectId});setNotice('Added to canvas.');}
  else{navigator.clipboard.writeText(url).then(()=>setNotice('Live preview link copied.')).catch(()=>setNotice(url));}
 }
 return <div className="shell">
  <aside><div className="brand">◈ <span>Components</span></div><div className="project">{manifest.name}</div><input aria-label="Search components" placeholder="Find a component…" value={search} onChange={e=>{setSearch(e.target.value);setSelected(null)}}/>
   <nav>{groups.map(g=><button className={g===group?'active':''} key={g} onClick={()=>{setGroup(g);setSelected(null)}}>{g==='All components'?'All components':g}<small>{manifest.components.filter(c=>g==='All components'||c.group===g).length}</small></button>)}</nav>
   <div className="aside-foot"><button onClick={()=>{setSelected(null);setGroup('Setup')}}>Preview setup</button></div>
  </aside>
  <main>{selected?<>
   <header><div><button className="back" onClick={()=>setSelected(null)}>← Components</button><h1>{selected.name}</h1><p>{selected.source}:{selected.line}</p></div><div className="actions"><input aria-label="Example name" placeholder="Name this example…" value={exampleName} onChange={e=>setExampleName(e.target.value)}/><button onClick={save}>Save</button><button className="primary" onClick={add}>{window.webkit?.messageHandlers?.componentCatalog?'Add to canvas':'Copy preview link'}</button></div></header>
   <div className="detail">
    <section className="stage-area"><div className="tools"><select aria-label="Example" value={variant} onChange={e=>{const name=e.target.value;setVariant(name);const example=(manifest.examples[selected.name]||[]).find(x=>x.name===name);setState(saved[selected.id]?.[name]||{...initial(selected,manifest,saved),args:example?.args||selected.defaults});}}><option>Default</option>{(manifest.examples[selected.name]||[]).filter(v=>v.name!=='Default').map(v=><option key={v.name}>{v.name}</option>)}{Object.keys(saved[selected.id]||{}).filter(n=>n!=='Default'&&!manifest.examples[selected.name]?.some(x=>x.name===n)).map(n=><option key={n}>{n}</option>)}</select>
     <select aria-label="Preview width" value={state.width} onChange={e=>setState(s=>({...s,width:+e.target.value}))}>{[320,390,640,960,1280].map(w=><option key={w} value={w}>{w} px</option>)}</select>
     <button aria-label="Toggle dark theme" onClick={()=>setState(s=>({...s,theme:s.theme==='light'?'dark':'light'}))}>{state.theme==='light'?'☀ Light':'☾ Dark'}</button>
     <button onClick={()=>{setState(initial(selected,manifest,saved));setVariant(manifest.examples[selected.name]?.[0]?.name||'Default');setEvents([])}}>Reset</button>
    </div><div className="stage"><iframe key={selected.id+retry} title={selected.name+' live preview'} ref={preview} style={{width:state.width}} src={previewURL(selected,state)} /></div>
    {renderErrors[selected.id]&&<div className="error"><strong>Needs setup</strong><p>{renderErrors[selected.id]}</p><span>Add missing data in Props, or connect providers in .webframes/preview.tsx.</span></div>}
    <button onClick={()=>{setRenderErrors(v=>{const next={...v};delete next[selected.id];return next});setReady(v=>({...v,[selected.id]:false}));setRetry(v=>v+1)}}>Retry preview</button><p className="hint">Component preview · server actions disabled; navigation is simulated.</p><section className="events"><h3>Interactions <span>{events.length}</span></h3>{events.length?events.map((e,i)=><div key={i}><time>{e.time}</time><code>{e.name}</code> {e.value}</div>):<p>Interact with the preview. Callback props appear here.</p>}</section>
    </section><section className="inspector"><h2>Props</h2>{selected.props.length?selected.props.map(p=><Prop key={selected.id+p.name} prop={p} value={state.args[p.name]} onChange={v=>change(p.name,v)}/>):<p>No locally declared prop types found. Use JSON to supply props.</p>}
    <details><summary>All props · JSON</summary><JSONControl value={state.args} onChange={args=>{if(args && typeof args==='object'&&!Array.isArray(args))setState(s=>({...s,args}));else throw Error('Use a JSON object.');}}/></details>
    <h3>Source references</h3><p className="hint">Files importing this component; not observed instances.</p>{selected.pages.length?selected.pages.map(p=><code className="source" key={p}>{p}</code>):<p>No direct file imports found.</p>}
    {Object.keys(saved[selected.id]||{}).length>0&&<details><summary>Saved examples</summary>{Object.keys(saved[selected.id]).map(n=><div className="saved" key={n}><span>{n}</span><button aria-label={'Delete '+n} onClick={()=>{const next=structuredClone(saved);delete next[selected.id][n];localStorage.setItem('wf:'+manifest.projectId,JSON.stringify(next));setSaved(next)}}>×</button></div>)}</details>}
    </section>
   </div>
  </>:group==='Setup'?<section className="setup"><h1>Project environment</h1><p>Previews render your exported React components directly. Nothing is copied into a replacement UI.</p><h2>Styles & providers</h2><p>Create <code>.webframes/preview.tsx</code> in your project when components need shared styles, a theme, or context. This file runs in every preview.</p><pre>{`import '../src/styles.css';\nimport {ThemeProvider} from '../src/theme';\n\nexport function Wrapper({children, theme}) {\n  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;\n}`}</pre><h2>Named examples</h2><p>Use <code>.webframes/catalog.json</code> for examples shared with the project. “Save example” stores a local example without editing source files.</p><pre>{JSON.stringify({examples:{Button:[{name:'Primary',args:{children:'Continue',variant:'primary'}}]}},null,2)}</pre><h2>Current support</h2><p>Navigation is simulated and server actions are disabled in isolated previews. Use the live page for server behavior. Client React components in TSX/JSX, local prop types, CSS imports, @/ and ~/ source aliases. Install your project dependencies first. Server components, framework-only modules, other alias rules and network data may need a preview adapter. Render failures are shown explicitly.</p></section>:<>
   <header><div><div className="eyebrow">PROJECT LIBRARY</div><h1>{group==='All components'?'All components':group}</h1><p>{visible.length} components · rendered from your source</p></div><button onClick={()=>location.reload()} aria-label="Refresh catalogue">↻ Refresh</button></header>
   {manifest.warnings.map(w=><div className="error" key={w}>{w}</div>)}
   {visible.length?<div className="grid">{visible.slice(page*12,(page+1)*12).map(c=>{const state=initial(c,manifest,saved);return <article key={c.id}><button className="tile" onClick={()=>open(c)} aria-label={'Open '+c.name}><div className="mini"><iframe tabIndex={-1} title={c.name+' thumbnail'} loading="lazy" src={previewURL(c,state)}/><span className="inspect">Inspect component ↗</span></div><div className="tile-info"><div><h2>{c.name}</h2><span>{c.props.length} props · {1+(manifest.examples[c.name]?.length||0)+Object.keys(saved[c.id]||{}).length} examples</span></div><span className={'dot '+(renderErrors[c.id]?'warn':ready[c.id]?'':'pending')} title={renderErrors[c.id]|| (ready[c.id]?'Preview ready':'Not yet rendered')}/></div><p className="tile-source">{c.source}</p>{renderErrors[c.id]&&<p className="preview-status">Needs setup · {renderErrors[c.id]}</p>}</button></article>})}</div>:<section className="empty"><h2>No components found</h2><p>{search?'Try a different name or folder.':'Export React components containing JSX from your project. Plain HTML pages remain available in the page map.'}</p></section>}
   {visible.length>12&&<nav className="pagination" aria-label="Component pages"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.ceil(visible.length/12)}</span><button disabled={(page+1)*12>=visible.length} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}
  </>}{notice&&<div role="status" className="toast" onClick={()=>setNotice('')}>{notice}</div>}</main>
 </div>
}
function Prop({prop:p,value,onChange}){return <label className="prop"><div><strong>{p.name}</strong>{p.required&&value===undefined&&<small>Required</small>}</div><code>{p.type}</code>{p.kind==='action'?<span className="hint">Logged in Interactions</span>:p.kind==='boolean'?<select aria-label={p.name} value={value===undefined?'unset':String(value)} onChange={e=>onChange(e.target.value==='unset'?undefined:e.target.value==='true')}><option value="unset">Use component default</option><option value="true">True</option><option value="false">False</option></select>:p.kind==='select'?<select aria-label={p.name} value={value===undefined?'':JSON.stringify(value)} onChange={e=>onChange(e.target.value===''?undefined:JSON.parse(e.target.value))}><option value="">Use component default</option>{p.options.map(v=><option key={JSON.stringify(v)} value={JSON.stringify(v)}>{String(v)}</option>)}</select>:p.kind==='json'?<JSONControl value={value} onChange={onChange}/>:<input aria-label={p.name} type={p.kind==='number'?'number':'text'} placeholder="Use component default" value={value??''} onChange={e=>onChange(p.kind==='number'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)}/>}</label>}
function JSONControl({value,onChange}){const [text,setText]=useState(JSON.stringify(value,null,2)||''),[error,setError]=useState('');useEffect(()=>setText(JSON.stringify(value,null,2)||''),[value]);return <><textarea spellCheck="false" aria-label="JSON props" value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{try{onChange(text?JSON.parse(text):undefined);setError('')}catch(e){setError(e.message)}}}/>{error&&<span className="input-error">{error}</span>}</>}
createRoot(document.getElementById('root')).render(<App/>);
